SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS db_neurophysio DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE db_neurophysio;

CREATE TABLE IF NOT EXISTS answer (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FK_Simu int(11) NOT NULL,
  FK_Quest int(11) NOT NULL,
  successful tinyint(1) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY ID (ID),
  UNIQUE KEY I_simu_quest (FK_Simu,FK_Quest),
  KEY I_quest (FK_Quest)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=307 ;

CREATE TABLE IF NOT EXISTS question (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FK_Theme int(11) NOT NULL,
  TextQuestion varchar(255) NOT NULL,
  Answer tinyint(1) NOT NULL,
  InsertDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  KEY I_theme (FK_Theme)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=105 ;

CREATE TABLE IF NOT EXISTS simulation (
  ID int(11) NOT NULL AUTO_INCREMENT,
  `Date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FK_Simu_NumberPhone int(11) DEFAULT NULL,
  FK_Simu_NumberServer int(11) DEFAULT NULL,
  FK_User int(11) NOT NULL,
  FK_Source int(11) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY FK_Simu_NumberPhone (FK_Simu_NumberPhone),
  KEY FK_Simu_NumberServer (FK_Simu_NumberServer),
  KEY FK_User (FK_User),
  KEY FK_Source (FK_Source)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=153 ;

CREATE TABLE IF NOT EXISTS `source` (
  ID int(11) NOT NULL AUTO_INCREMENT,
  FK_Type int(11) NOT NULL,
  IPAddress varchar(255) NOT NULL,
  PRIMARY KEY (ID),
  KEY FK_Type (FK_Type)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=236 ;

CREATE TABLE IF NOT EXISTS statut (
  ID int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  Simulation int(11) NOT NULL,
  UserStatistics int(11) NOT NULL,
  ClassStatistics int(11) NOT NULL,
  Question int(11) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

CREATE TABLE IF NOT EXISTS theme (
  ID int(11) NOT NULL AUTO_INCREMENT,
  Number int(11) NOT NULL,
  `Name` varchar(255) NOT NULL,
  OpenToSimulation tinyint(1) NOT NULL,
  PRIMARY KEY (ID),
  KEY Number (Number)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

CREATE TABLE IF NOT EXISTS `type` (
  ID int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

CREATE TABLE IF NOT EXISTS `user` (
  ID int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  Firstname varchar(255) NOT NULL,
  Login varchar(255) NOT NULL,
  Email varchar(255) NOT NULL,
  `Password` varchar(255) NOT NULL,
  RegistrationDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FK_Statut int(11) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY Login (Login),
  UNIQUE KEY Email (Email),
  KEY FK_Statut (FK_Statut)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;


ALTER TABLE answer
  ADD CONSTRAINT answer_ibfk_1 FOREIGN KEY (FK_Simu) REFERENCES simulation (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT answer_ibfk_2 FOREIGN KEY (FK_Quest) REFERENCES question (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE question
  ADD CONSTRAINT question_ibfk_1 FOREIGN KEY (FK_Theme) REFERENCES theme (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE simulation
  ADD CONSTRAINT simulation_ibfk_1 FOREIGN KEY (FK_Simu_NumberPhone) REFERENCES simulation (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT simulation_ibfk_2 FOREIGN KEY (FK_Simu_NumberServer) REFERENCES simulation (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT simulation_ibfk_3 FOREIGN KEY (FK_User) REFERENCES `user` (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT simulation_ibfk_4 FOREIGN KEY (FK_Source) REFERENCES source (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE source
  ADD CONSTRAINT source_ibfk_1 FOREIGN KEY (FK_Type) REFERENCES type (ID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE user
  ADD CONSTRAINT user_ibfk_1 FOREIGN KEY (FK_Statut) REFERENCES statut (ID) ON DELETE CASCADE ON UPDATE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
